### ISSUE TITLE
Error when finalizing Workflow

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/tidyclust#89] opened 2022-11-16 17:55 UTC
After tuning a workflow with `tune_cluster(workflow, ...)` and then trying to finalize it with `workflow %>% finalize_workflow_tidyclust(best_params)`, where `best_params <- tibble(num_clusters = 10)`, The following message appears:
```
Error in parsnip::update_engine_parameters(object$eng_args, ...) : 
  argument "fresh" is missing, with no default
```

**Comment by EmilHvitfeldt** [comment] 2022-11-16 19:57
Hello @nipnipj 👋  I'm not able to reproduce this error on my end. Would you be able to create a reprex? Thank you!

``` r
library(tidymodels)
library(tidyclust)
#> 
#> Attaching package: 'tidyclust'
#> The following object is masked from 'package:parsnip':
#> 
#>     prepare_data

kmeans_spec <- k_means(num_clusters = tune())

kmeans_wf <- workflow(~., kmeans_spec)

my_num <- tibble(num_clusters = 2)

finalize_workflow_tidyclust(kmeans_wf, my_num)
#> ══ Workflow ════════════════════════════════════════════════════════════════════
#> Preprocessor: Formula
#> Model: k_means()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> ~.
#> 
#> ── Model ───────────────────────────────────────────────────────────────────────
#> K Means Cluster Specification (partition)
#> 
#> Main Arguments:
#>   num_clusters = 2
#> 
#> Computational engine: stats
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by nipnipj** [comment] 2022-11-16 22:21
Hi, @EmilHvitfeldt.

``` r
library(tidyverse)
library(tidymodels)
library(tidyclust)
#> 
#> Attaching package: 'tidyclust'
#> The following object is masked from 'package:parsnip':
#> 
#>     prepare_data

data("penguins", package = "modeldata")
data <- penguins %>%
  as_tibble() %>%
  drop_na()

rec <- data %>%  
  recipe(~ bill_length_mm + bill_depth_mm) %>% 
  step_normalize(all_numeric_predictors())

model <- k_means(
  num_clusters = tune()
  ) %>%
  set_engine("stats", algorithm = "Lloyd", iter.max = 50) 

learner <- workflow() %>% 
  add_recipe(rec) %>% 
  add_model(model)

custom_grid <- crossing(
  num_clusters = seq(2, 10, 1)
)

cv_folds <- data %>%
  vfold_cv(v = 3, repeats = 1)

at <- tune_cluster(
  learner,
  resamples = cv_folds,
  grid = custom_grid,
  control = control_grid(save_pred = TRUE, extract = identity),
  metrics = cluster_metric_set(sse_within_total, sse_total, sse_ratio)
)

best <- tibble(
  num_clusters = 2
)
final_learner <- learner %>% finalize_workflow_tidyclust(best)
#> Error in parsnip::update_engine_parameters(object$eng_args, ...): argument "fresh" is missing, with no default
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by EmilHvitfeldt** [comment] 2022-11-16 22:43
Thank you! This should be fixed in https://github.com/tidymodels/tidyclust/pull/90, will merge once the CI runs clean

**Closed** 2022-11-16 23:29 UTC
Labels: bug, reprex
